//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/00_GameData/Inputs/I_Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @I_Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @I_Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""I_Player"",
    ""maps"": [
        {
            ""name"": ""Locomotion"",
            ""id"": ""0841ac91-0276-4988-b184-888ba184a245"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""83e9a79a-6db1-46bf-988d-c86824116557"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9a6ef78e-608b-4b8c-b635-c754b34096be"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8cf7bc1a-ac54-4557-bd9a-2d737f3ca662"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Light"",
                    ""type"": ""Button"",
                    ""id"": ""c300a47f-18f8-4ee0-9d1e-d908f2faf726"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Heavy"",
                    ""type"": ""Button"",
                    ""id"": ""d55fce7c-7345-4536-ba66-18180ee084f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Magic"",
                    ""type"": ""Button"",
                    ""id"": ""bb5b6c02-297d-4974-95d9-d4bc3667dbf0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""bda7c571-704b-44a4-9117-c3bc37b12e40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeTargeting"",
                    ""type"": ""Button"",
                    ""id"": ""ac5fbc40-4b2e-48a2-bda4-34e3eae3a214"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tool_Up"",
                    ""type"": ""Button"",
                    ""id"": ""1bdff915-9c37-4dd8-b946-5fe1ecc34b18"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tool_Right"",
                    ""type"": ""Button"",
                    ""id"": ""af94bec3-2146-4151-8ba4-1748d63924e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tool_Down"",
                    ""type"": ""Button"",
                    ""id"": ""a958cad8-91be-445a-8bb0-bbeb4129a824"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tool_Left"",
                    ""type"": ""Button"",
                    ""id"": ""941d60d6-d992-4ab6-9a64-bbc06ce9ef2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Main"",
                    ""type"": ""Button"",
                    ""id"": ""23b6a453-ac45-4e0e-8b38-21c36a8874bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e61d864a-17f1-45cd-9523-ccb6af8ee036"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Back"",
                    ""type"": ""Button"",
                    ""id"": ""3058b835-2c0b-49ca-ae16-6241541ef77b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_TabChange"",
                    ""type"": ""Value"",
                    ""id"": ""dfa92aa0-c826-4bc2-8017-bd600757221c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""b13fe535-7263-4009-a51f-d093011557c5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0ef3fc55-e0e7-4b63-b41f-3ba1305f19af"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a8653470-01c2-474f-9152-aa2acbdfdca8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9a785b6a-e46c-483a-bfd6-ae1aa4ac464c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""742af509-637e-4f98-a457-29b99e03d44b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""4e8e5cae-e5cd-460a-8cc2-7545fd776dca"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7e0ebd16-d4f0-4404-a26d-ab28069055bb"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""db5a0716-df91-476c-9212-71fb6e3e3203"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""48a10e1f-89d4-4b7c-9078-c626414fc433"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a1defc2c-9f0b-4fab-80c1-302198cd1b85"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""92cef3f0-7cd2-404c-af56-ea0fd78f957a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertY=false),ScaleVector2(x=0.25,y=0.25)"",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ff6875c-ad97-4ae2-890a-c73f61b9a0d6"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2,ScaleVector2(x=0.8,y=0.6),StickDeadzone(min=0.175)"",
                    ""groups"": ""Controller"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8034b91-3e7d-44e3-aaa6-e6488a8ca057"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29a01de7-c1b9-4f73-9e32-c05d8ed9fdb9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b88a9fe7-0ebe-4ec7-9622-a6b8f7d0d53b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Attack_Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f700c7f8-cb76-481b-ab4b-4cace9c9a4da"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Attack_Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cc75ff9-11f4-4c73-b634-9f0c863fcdeb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Attack_Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22e750cc-9be2-4bab-89cc-8fe096b15733"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Attack_Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5031b1e-c6ea-4507-b18f-32e8b9a77a15"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Tool_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f093fa8-e54e-447b-8bd6-ddc07b4e8a9c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Tool_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1130c509-8457-40ee-9a04-92a7fc635cc6"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Tool_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5019c127-586d-4fcc-a387-c75c3295c8bb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Tool_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78934d23-3ecc-4c30-a141-5baccb167cbd"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Tool_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1dbd1eb-bafd-4bfa-93b5-dbd6a72e8b5f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Tool_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ee5ee20-05b6-4da7-b74d-5f683735e44e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Tool_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3e594a1-f699-48c8-a5d3-e8e9de137683"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Tool_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81e2de7a-0067-4e7c-8cc3-3ced928a32c1"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f191f184-aa25-4fe4-8451-b8aecbb38545"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cc25a15-b209-4393-a072-63059eff6738"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Magic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1f05257-a2c8-4133-ac80-a0a5af3bb3eb"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Magic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ef0ec36-53e6-473b-a0a5-9882138b53eb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UI_Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f41d60db-299e-4086-b212-b2ca328b5def"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dad1c0eb-a2ea-4392-8cf6-90e3e5ad2bbe"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UI_Main"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e22ff47-8530-4bf5-b805-35135ccf3a2c"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_Main"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4578e11f-c9ec-4429-9384-8e9de085edf9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ChangeTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bf2117d-fe7e-42f0-bc50-0316a10d7ddd"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ChangeTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""366835e7-d55d-4e2a-8c00-a61e57713c13"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UI_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""764e461f-c3a3-4dc3-b5bb-3150c7fe5022"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ccfbb62-06d5-4c7e-ae5e-1428434592d7"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a01622dc-5e90-49ff-bcea-f28d69a770b3"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""deba2ef2-bad7-4607-aabe-dc07cbceeba7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1fed99dc-11c3-4b95-9de9-dbbfce911168"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""43982134-7e89-4519-9884-96849a5df548"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Xbox"",
                    ""id"": ""dde924f3-0f18-45c3-a8de-fd1dd0ee046c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b77c55f5-9fa0-4238-8f94-9fc5fc9796bb"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""056cff03-db98-443b-9d2a-5f8eb50857ae"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""PlayStation"",
                    ""id"": ""4574d9ac-a7b6-4e62-90b7-468ff118ba81"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6c10547d-3cba-4476-bf57-6de9fb5b66e2"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""92d2110e-a892-4cbc-a311-3fa88f21ed74"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Switch"",
                    ""id"": ""59dae696-fde4-4041-8b87-7d2dcf914833"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""152d5f11-458a-4d0c-94b8-1377a8c9ba34"",
                    ""path"": ""<SwitchProControllerHID>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ce41107c-a4e2-4740-929a-253869888eed"",
                    ""path"": ""<SwitchProControllerHID>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""UI_TabChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Locomotion
        m_Locomotion = asset.FindActionMap("Locomotion", throwIfNotFound: true);
        m_Locomotion_Look = m_Locomotion.FindAction("Look", throwIfNotFound: true);
        m_Locomotion_Move = m_Locomotion.FindAction("Move", throwIfNotFound: true);
        m_Locomotion_Jump = m_Locomotion.FindAction("Jump", throwIfNotFound: true);
        m_Locomotion_Attack_Light = m_Locomotion.FindAction("Attack_Light", throwIfNotFound: true);
        m_Locomotion_Attack_Heavy = m_Locomotion.FindAction("Attack_Heavy", throwIfNotFound: true);
        m_Locomotion_Magic = m_Locomotion.FindAction("Magic", throwIfNotFound: true);
        m_Locomotion_Dodge = m_Locomotion.FindAction("Dodge", throwIfNotFound: true);
        m_Locomotion_ChangeTargeting = m_Locomotion.FindAction("ChangeTargeting", throwIfNotFound: true);
        m_Locomotion_Tool_Up = m_Locomotion.FindAction("Tool_Up", throwIfNotFound: true);
        m_Locomotion_Tool_Right = m_Locomotion.FindAction("Tool_Right", throwIfNotFound: true);
        m_Locomotion_Tool_Down = m_Locomotion.FindAction("Tool_Down", throwIfNotFound: true);
        m_Locomotion_Tool_Left = m_Locomotion.FindAction("Tool_Left", throwIfNotFound: true);
        m_Locomotion_UI_Main = m_Locomotion.FindAction("UI_Main", throwIfNotFound: true);
        m_Locomotion_UI_Pause = m_Locomotion.FindAction("UI_Pause", throwIfNotFound: true);
        m_Locomotion_UI_Back = m_Locomotion.FindAction("UI_Back", throwIfNotFound: true);
        m_Locomotion_UI_TabChange = m_Locomotion.FindAction("UI_TabChange", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Locomotion
    private readonly InputActionMap m_Locomotion;
    private List<ILocomotionActions> m_LocomotionActionsCallbackInterfaces = new List<ILocomotionActions>();
    private readonly InputAction m_Locomotion_Look;
    private readonly InputAction m_Locomotion_Move;
    private readonly InputAction m_Locomotion_Jump;
    private readonly InputAction m_Locomotion_Attack_Light;
    private readonly InputAction m_Locomotion_Attack_Heavy;
    private readonly InputAction m_Locomotion_Magic;
    private readonly InputAction m_Locomotion_Dodge;
    private readonly InputAction m_Locomotion_ChangeTargeting;
    private readonly InputAction m_Locomotion_Tool_Up;
    private readonly InputAction m_Locomotion_Tool_Right;
    private readonly InputAction m_Locomotion_Tool_Down;
    private readonly InputAction m_Locomotion_Tool_Left;
    private readonly InputAction m_Locomotion_UI_Main;
    private readonly InputAction m_Locomotion_UI_Pause;
    private readonly InputAction m_Locomotion_UI_Back;
    private readonly InputAction m_Locomotion_UI_TabChange;
    public struct LocomotionActions
    {
        private @I_Player m_Wrapper;
        public LocomotionActions(@I_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Locomotion_Look;
        public InputAction @Move => m_Wrapper.m_Locomotion_Move;
        public InputAction @Jump => m_Wrapper.m_Locomotion_Jump;
        public InputAction @Attack_Light => m_Wrapper.m_Locomotion_Attack_Light;
        public InputAction @Attack_Heavy => m_Wrapper.m_Locomotion_Attack_Heavy;
        public InputAction @Magic => m_Wrapper.m_Locomotion_Magic;
        public InputAction @Dodge => m_Wrapper.m_Locomotion_Dodge;
        public InputAction @ChangeTargeting => m_Wrapper.m_Locomotion_ChangeTargeting;
        public InputAction @Tool_Up => m_Wrapper.m_Locomotion_Tool_Up;
        public InputAction @Tool_Right => m_Wrapper.m_Locomotion_Tool_Right;
        public InputAction @Tool_Down => m_Wrapper.m_Locomotion_Tool_Down;
        public InputAction @Tool_Left => m_Wrapper.m_Locomotion_Tool_Left;
        public InputAction @UI_Main => m_Wrapper.m_Locomotion_UI_Main;
        public InputAction @UI_Pause => m_Wrapper.m_Locomotion_UI_Pause;
        public InputAction @UI_Back => m_Wrapper.m_Locomotion_UI_Back;
        public InputAction @UI_TabChange => m_Wrapper.m_Locomotion_UI_TabChange;
        public InputActionMap Get() { return m_Wrapper.m_Locomotion; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LocomotionActions set) { return set.Get(); }
        public void AddCallbacks(ILocomotionActions instance)
        {
            if (instance == null || m_Wrapper.m_LocomotionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LocomotionActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Attack_Light.started += instance.OnAttack_Light;
            @Attack_Light.performed += instance.OnAttack_Light;
            @Attack_Light.canceled += instance.OnAttack_Light;
            @Attack_Heavy.started += instance.OnAttack_Heavy;
            @Attack_Heavy.performed += instance.OnAttack_Heavy;
            @Attack_Heavy.canceled += instance.OnAttack_Heavy;
            @Magic.started += instance.OnMagic;
            @Magic.performed += instance.OnMagic;
            @Magic.canceled += instance.OnMagic;
            @Dodge.started += instance.OnDodge;
            @Dodge.performed += instance.OnDodge;
            @Dodge.canceled += instance.OnDodge;
            @ChangeTargeting.started += instance.OnChangeTargeting;
            @ChangeTargeting.performed += instance.OnChangeTargeting;
            @ChangeTargeting.canceled += instance.OnChangeTargeting;
            @Tool_Up.started += instance.OnTool_Up;
            @Tool_Up.performed += instance.OnTool_Up;
            @Tool_Up.canceled += instance.OnTool_Up;
            @Tool_Right.started += instance.OnTool_Right;
            @Tool_Right.performed += instance.OnTool_Right;
            @Tool_Right.canceled += instance.OnTool_Right;
            @Tool_Down.started += instance.OnTool_Down;
            @Tool_Down.performed += instance.OnTool_Down;
            @Tool_Down.canceled += instance.OnTool_Down;
            @Tool_Left.started += instance.OnTool_Left;
            @Tool_Left.performed += instance.OnTool_Left;
            @Tool_Left.canceled += instance.OnTool_Left;
            @UI_Main.started += instance.OnUI_Main;
            @UI_Main.performed += instance.OnUI_Main;
            @UI_Main.canceled += instance.OnUI_Main;
            @UI_Pause.started += instance.OnUI_Pause;
            @UI_Pause.performed += instance.OnUI_Pause;
            @UI_Pause.canceled += instance.OnUI_Pause;
            @UI_Back.started += instance.OnUI_Back;
            @UI_Back.performed += instance.OnUI_Back;
            @UI_Back.canceled += instance.OnUI_Back;
            @UI_TabChange.started += instance.OnUI_TabChange;
            @UI_TabChange.performed += instance.OnUI_TabChange;
            @UI_TabChange.canceled += instance.OnUI_TabChange;
        }

        private void UnregisterCallbacks(ILocomotionActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Attack_Light.started -= instance.OnAttack_Light;
            @Attack_Light.performed -= instance.OnAttack_Light;
            @Attack_Light.canceled -= instance.OnAttack_Light;
            @Attack_Heavy.started -= instance.OnAttack_Heavy;
            @Attack_Heavy.performed -= instance.OnAttack_Heavy;
            @Attack_Heavy.canceled -= instance.OnAttack_Heavy;
            @Magic.started -= instance.OnMagic;
            @Magic.performed -= instance.OnMagic;
            @Magic.canceled -= instance.OnMagic;
            @Dodge.started -= instance.OnDodge;
            @Dodge.performed -= instance.OnDodge;
            @Dodge.canceled -= instance.OnDodge;
            @ChangeTargeting.started -= instance.OnChangeTargeting;
            @ChangeTargeting.performed -= instance.OnChangeTargeting;
            @ChangeTargeting.canceled -= instance.OnChangeTargeting;
            @Tool_Up.started -= instance.OnTool_Up;
            @Tool_Up.performed -= instance.OnTool_Up;
            @Tool_Up.canceled -= instance.OnTool_Up;
            @Tool_Right.started -= instance.OnTool_Right;
            @Tool_Right.performed -= instance.OnTool_Right;
            @Tool_Right.canceled -= instance.OnTool_Right;
            @Tool_Down.started -= instance.OnTool_Down;
            @Tool_Down.performed -= instance.OnTool_Down;
            @Tool_Down.canceled -= instance.OnTool_Down;
            @Tool_Left.started -= instance.OnTool_Left;
            @Tool_Left.performed -= instance.OnTool_Left;
            @Tool_Left.canceled -= instance.OnTool_Left;
            @UI_Main.started -= instance.OnUI_Main;
            @UI_Main.performed -= instance.OnUI_Main;
            @UI_Main.canceled -= instance.OnUI_Main;
            @UI_Pause.started -= instance.OnUI_Pause;
            @UI_Pause.performed -= instance.OnUI_Pause;
            @UI_Pause.canceled -= instance.OnUI_Pause;
            @UI_Back.started -= instance.OnUI_Back;
            @UI_Back.performed -= instance.OnUI_Back;
            @UI_Back.canceled -= instance.OnUI_Back;
            @UI_TabChange.started -= instance.OnUI_TabChange;
            @UI_TabChange.performed -= instance.OnUI_TabChange;
            @UI_TabChange.canceled -= instance.OnUI_TabChange;
        }

        public void RemoveCallbacks(ILocomotionActions instance)
        {
            if (m_Wrapper.m_LocomotionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILocomotionActions instance)
        {
            foreach (var item in m_Wrapper.m_LocomotionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LocomotionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LocomotionActions @Locomotion => new LocomotionActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface ILocomotionActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack_Light(InputAction.CallbackContext context);
        void OnAttack_Heavy(InputAction.CallbackContext context);
        void OnMagic(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnChangeTargeting(InputAction.CallbackContext context);
        void OnTool_Up(InputAction.CallbackContext context);
        void OnTool_Right(InputAction.CallbackContext context);
        void OnTool_Down(InputAction.CallbackContext context);
        void OnTool_Left(InputAction.CallbackContext context);
        void OnUI_Main(InputAction.CallbackContext context);
        void OnUI_Pause(InputAction.CallbackContext context);
        void OnUI_Back(InputAction.CallbackContext context);
        void OnUI_TabChange(InputAction.CallbackContext context);
    }
}
